version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 8080
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
